DROP DATABASE IF EXISTS taxi_trips;
DROP DATABASE IF EXISTS tpcc;
DROP DATABASE IF EXISTS ycsb;

CREATE DATABASE taxi_trips;
CREATE DATABASE tpcc;
CREATE DATABASE ycsb;

CREATE USER whatif WITH PASSWORD 'mahif';
GRANT ALL PRIVILEGES ON DATABASE taxi_trips TO whatif;
GRANT ALL PRIVILEGES ON DATABASE tpcc TO whatif;
GRANT ALL PRIVILEGES ON DATABASE ycsb TO whatif;