CREATE DATABASE whatif;
CREATE DATABASE tpcc;
CREATE DATABASE ycsb;

CREATE USER whatif WITH PASSWORD 'mahif';
GRANT ALL PRIVILEGES ON DATABASE whatif TO whatif;
GRANT ALL PRIVILEGES ON DATABASE tpcc TO whatif;
GRANT ALL PRIVILEGES ON DATABASE ycsb TO whatif;